### ISSUE TITLE
Can not fill crew on launchpad.

### ISSUE THREAD

**Issue by georgir** [PapaJoesSoup/ShipManifest#14]
The most basic and yet most important use of this type of mods is filling the command pods of a craft on the launch pad if you launched when you forgot to select crew.
It is especially important with KCT when you would not want to waste time for recover/recondition/re-rollout.

It just does not work with the current version of Ship Manifest.
In roster list, "add disabled. no source part is selected"
But a source part does not make sense for this - the source is the roster not another ship part.

**Comment by PapaJoesSoup** [comment]
Hi geogir,  I'm sorry you are encountering difficulties.  The following link will explain how this process works.  https://github.com/PapaJoesSoup/ShipManifest/wiki/1.5---Roster-Window

This explains how the Roster window operates.  The functionality you are looking for does exist.

If you are wanting to add a kerbal to a vessel (meaning they are currently available), then you do need to specify a source part.   Since SM is themed around a vessel in flight or in assembly, the scope of kerbal roster features is limited.

The reason you need to specify a source part is due to the fact tha s ship can have multiple parts that can be crewed (science labs, passenger containers, etc.  So sm cannot "assume" you mean the command pod.  Therefore you need to specify the part you want to place the crewmember.

All this is affected by the Realism Mode setting.  Finally, if you want to fully crew a vessel with one click, then turn off Realism and in preflight buttons will appear to allow you to fill or empty the crew with one click.

**Comment by georgir** [comment]
Thanks for the reply,
Unfortunately the info in that link does not help any, and the mod behavior is not as described there.
When I select a source part the add buttons for my available kerbals in the roster simply get replaced by '---' buttons.

I also tried selecting my pod as a "target" part, as calling the part where you want to add the kerbals "source" instead of "destination" or "target" is illogical, but that did not do anything.

The "empty" button did indeed work OK to remove the current crew, but the "fill" button did not do anything.

Tried turning off the realism checkbox as well - it made no difference.

**Comment by PapaJoesSoup** [comment]
Thanks for the reply. I will make sure that this is resolved in the upcoming release. I did a major refactor so I did touch that area of the code.

**Comment by PapaJoesSoup** [comment]
Release soon.   Fixed my performance issue.

**Comment by PapaJoesSoup** [comment]
Has this been resolved for you with the latest release?

**Comment by georgir** [comment]
since I'm not playing ksp much now and just waiting for 1.1 I hadn't tested.
just replaced it in my gamedata folder, now I don't get any shipmanifest
buttons in my toolbar.
probably didn't install something quite right, tho i'm not sure what -
folder structure seems ok.
if I get more time later i'll retest.

**Comment by georgir** [comment]
looking at the description of the last release has me confused - removed
some dll, supposedly replaced by "smwrapper" but theres no smwrapper in the
gamedata folder? theres a c sharp source file for one in the archive but no
compiled dll

**Comment by PapaJoesSoup** [comment]
Sorry for the confusion.  The dll file I'm referring to are for Mod developer use.  they do not affect the use of SM in general.  The SMWrapper.cs file is used by Mod developers to make it easy to consume the public code interface of SM. It will not be in GameData anywhere and is part of the root of the distribution zip.

So, you only need ShipManifest.dll and SMInterface.dll in your GameData\ShipManifest\Plugins folder.

If you delete the SM folder and install the mod by overwriting the gamedata folder, all will be well.
