### ISSUE TITLE
Feature Request: Window resize

### ISSUE THREAD

**Issue by AlexForgotMyAccountCreatedATempOne** [PapaJoesSoup/ShipManifest#45]
Would be a good idea to add resize feature to main window and especially transfer window.
At least via config file.
As of now changing size in config file just resizes borders of respected windows content stay at same size and place. (tested on transfer window)

My problem originally was the same as this guy:
https://forum.kerbalspaceprogram.com/index.php?/topic/56643-130-ship-manifest-crew-science-resources-v-5200-17-jul-17/&do=findComment&comment=3015919
Lots of parts, tity window, much scroll.

Thanks for the mod btw, been using it since forever, much appreciated for your work.

**Comment by PapaJoesSoup** [comment]
Thanks for the feedback.  resizing is going to be an interesting challenge.  so much of the imgui code is tied to fixed values.  I will have to spend a bit of time getting the values converted to vars that I can manage. then it may be possible to perform some sort of resize.

In the post you referenced, I asked some questions about what you would expect in a resize feature.  I never received any replies, so any input as to how it should behave would be welcome.  I suspect the greatest need is for the scroll boxes to resize and leave the details alone, since they do not really need to be altered.  However, if we resize horizontally as well as vertically, that then presents a need to alter the details sections also.

Thoughts?

**Comment by PapaJoesSoup** [comment]
Manifest and Transfer WIndows resizable as of release 6.0.5.0.  All windows are resizable as of release 6.0.6.0
